#!/bin/sh

yell() { echo ": $*" >&2; }
die () { yell "$*"; exit 111; }
try () { "$@" || die "cannot $*" ; }

testconfig () {
    if [ ! -f blogconfig ]; then
        return 1
    fi
    blogtitle=`try sed -n 's/blogtitle: *//p' blogconfig`
    postdirs=`try sed -n 's/postdirs: *//p' blogconfig`
    baseurl=`try sed -n 's/baseurl: *//p' blogconfig`
    destination=`try sed -n 's/destination: *//p' blogconfig`
    if   [ "$blogtitle"   = "" ]; then
        echo No blogtitle given
        return 1
    elif [ "$postdirs"    = "" ]; then
        echo No postdirectories defined
        return 1
    elif [ "$baseurl"     = "" ]; then
        echo "No baseurl given (even a dummy one is necessary for local)"
        return 1
    elif [ "$destination" = "" ]; then
        echo "No destination given (even a dummy one is necessary for local)"
        return 1
    fi
}

printusage () {
cat << EOF
possible actions:
    make:
        produce the blog from the blogconfig (must be in current folder)
    deploy:
        move the blog to the destination directory (may need root priveleges).
    template :
EOF
blog template
}


try testconfig

case "$1" in
    deploy)
    if [ $# -gt 1 ]; then
        printusage
    else 
        blog-deploy
    fi
    ;;
    template)
    nargs=`echo $@ | sed 's/^template//'`
    blog-template $nargs
    ;;
    make)
    if [ $# -gt 1 ]; then
        printusage
    else 
        blog-make
    fi
    ;;
    *)
    printusage
    ;;
esac

# vi: syntax=sh et ts=4 sts=4 sw=4
