#!/bin/sh

yell() { echo ": $*" >&2; }
die () { yell "$*"; exit 111; }
try () { "$@" || die "cannot $*" ; }

destination=`try sed -n 's/destination: *//p' blogconfig`
payloads=`try sed -n 's/payloads: *//p' blogconfig`

installpayload () {
	filename=$1
	if [ -f $filename ]; then
			install -D -m 500 -o www -g www $filename $destination/$filename
	elif [ -d $filename ]; then
		for f in `ls $filename/* 2>/dev/null`; do
			installpayload $f
		done
	fi
}

for p in $payloads; do
	installpayload $p
done


for file in cache/*.html;
do
	filename=${file##cache/}
	install -m 500 -o www -g www cache/$filename $destination/$filename
done
